config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
require './lib/contentful_client'

class Recipe < ApplicationRecord
  def recipes
    ContentfulClient.recipes content_type
  end

  def self.find_recipe(content_id)
    ContentfulClient.recipe content_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ExceptionHandler
  include Pagy::Backend
end

app/controllers/concerns/exception_handler.rb
# frozen_string_literal: true

module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from Contentful::AccessDenied do |e|
      render json: { message: e.message }, status: :forbidden
    end

    rescue_from Contentful::BadGateway do |e|
      render json: { message: e.message }, status: :bad_gateway
    end

    rescue_from Contentful::BadRequest do |e|
      render json: { message: e.message }, status: :bad_request
    end

    rescue_from Contentful::Error do |e|
      render json: { message: e.message }, status: :not_acceptable
    end

    rescue_from Contentful::NotFound do |e|
      render json: { message: e.message }, status: :not_found
    end

    rescue_from Contentful::RateLimitExceeded do |e|
      render json: { message: e.message }, status: :upgrade_required
    end

    rescue_from Contentful::UnparsableResource do |e|
      render json: { message: e.message }, status: :unprocessable_entity
    end

    rescue_from Contentful::ServerError do |e|
      render json: { message: e.message }, status: :internal_server_error
    end

    rescue_from Contentful::ServiceUnavailable do |e|
      render json: { message: e.message }, status: :service_unavailable
    end

    rescue_from Contentful::Unauthorized do |e|
      render json: { message: e.message }, status: :unauthorized
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show]

  def index
    @pagy, @recipes = pagy_array(Recipe.first.recipes, items: 2)
  end

  def show
    set_chef
    set_tags
  end

  private

  def set_chef
    begin
      @chef = @recipe.chef
    rescue Contentful::EmptyFieldError => e
      @chef = nil
    end
  end

  def set_tags
    begin
      @tags = @recipe.tags.map(&:name).join(', ')
    rescue Contentful::EmptyFieldError => e
      @tags = nil
    end
  end

  def set_recipe
    @recipe = Recipe.find_recipe(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.slim
doctype html
html
head
  title ContentfulRecipe
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag('//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css')
  = javascript_include_tag('//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js')
  = csrf_meta_tags

body
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        = link_to 'Home', recipes_path, class: "navbar-brand"

  .container
    == yield

app/views/recipes/index.html.slim
h1 Listing Contentful Configurations

table.table.table-striped
  thead
    tr
      th Name
      th Image
      th Show

  tbody
    - @recipes.each do |recipe|
      tr
        td = recipe.title
        td = image_tag recipe.photo.url, class: "img_preview"
        td = link_to 'Show' , recipe_path(recipe.id)

== pagy_bootstrap_nav(@pagy)

app/views/recipes/show.html.slim
h1 Recipe

.row
  .col-xs-6.col-md-6.col-lg-6
    h1
      = image_tag @recipe.photo.url, class: "img_show"

  .col-xs-6.col-md-6.col-lg-6
    h1 Name
    h4 = @recipe.title

    h1 List of Tags
    h4 = @tags

    h1 Description
    h4 = @recipe.description

    h1 Chef Name
    h4 = @chef&.name